name: cicd terraform
on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  terraform:
    name: terraform-actions(v1)
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: infrastructure


    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.0.1
            terraform_wrapper: false


        #Terraform commands
      - name: Initialize Terraform
        run: |
          terraform init -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
                         -backend-config="key=${{ secrets.TF_BACKEND_KEY }}" \
                         -backend-config="region=${{ secrets.TF_BACKEND_REGION }}" \
                         -backend-config="dynamodb_table=${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}"
      - name: Terraform Refresh
        id: refresh
        run: terraform refresh

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
      
      - name: Terraform Apply
        id: apply
        run: |
          if [ "${{github.event_name}}" == "push" ] && [ "${{github.ref}}" == "refs/heads/main" ]; then 
          terraform apply tfplan || exit 1
          else
            echo "Skipping Terraform apply."
          fi

      