name: cicd terraform
on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  terraform:
    name: terraform-actions(v1)
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: infrastructure


    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.0.1
            terraform_wrapper: false

        #Creates backend
      - name: Create Backend.tfvars file
        run: echo "${{ secrets.BACKEND_TFVARS }}" > backend.tfvars
        
        #Terraform commands
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend.tfvars

      - name: Terraform Refresh
        id: refresh
        run: terraform refresh -var-file=backend.tfvars

      - name: Terraform Format
        id: fmt
        run: terraform fmt  -var-file=backend.tfvars

      - name: Terraform Validate
        run: terraform validate -var-file=backend.tfvars

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=backend.tfvars -out=tfplan
      
      - name: Terraform Apply
        id: apply
        run: |
          if [ "${{github.event_name}}" == "push" ] && [ "${{github.ref}}" == "refs/heads/main" ]; then 
          terraform apply -var-file=backend.tfvars tfplan || exit 1
          else
            echo "Skipping Terraform apply."
          fi

      