name: destory terraform resources
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  terraform:
    name: terraform-destroy
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: infrastructure


    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.0.1
            terraform_wrapper: false



      #Creates backend
      - name: Create Backend.tfvars file
        run: echo "${{ secrets.BACKEND_TFVARS }}" > backend.tfvars
      

      #Terraform commands
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend.tfvars


      - name: Terraform Destroy
        id: destroy
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          terraform destroy -var-file=backend.tfvars -auto-approve || echo "Terraform destroy complete, unable to rewrite state file as backend infrastrcutre is deleted."



