name: destory terraform resources
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  terraform:
    name: terraform-destroy
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: infrastructure


    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.0.1
            terraform_wrapper: false


      - name: Terraform Destroy
        id: destroy
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          terraform destroy -auto-approve



